version: "2.1"
volumes:
  webapp-data: {}
networks:
  backing-services:
    driver: bridge
services:
  webapp:
    build:
      context: ..
      dockerfile: .mvn/Dockerfile
    volumes: ["webapp-data:/home"]
    ports: ["5005:5005",
            "8080:8080",
            "9990:9990"]
    mem_limit: 786432000 # container limit: 750Mb (750 * 1024 * 1024)
    networks: [backing-services]
