sudo: required
group: travis_lts

env:
  global:
    TERM=dumb

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  - wget get.docker.com -O- | sudo sh -
  - sudo usermod -aG docker $(whoami)
  - sudo apt -y install curl jq libxml2-utils python-pip
  - sudo pip install docker-compose httpie
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 5432 5672 27017

script:
  - export base=$(pwd)

  # using-conventions
  - cd ${base}/using-conventions
  - bash gradlew clean build
  - bash mvnw clean package
  - docker-compose build --force-rm --no-cache --pull
  - docker-compose up --force-recreate --remove-orphans &
  - sleep 30
  - http :8080/webapp/
  - http :8080/webapp/hello
  - http :8080/webapp/customers/list
  - docker-compose down -v

  # render-property-from-action
  - cd ${base}/render-property-from-action
  - bash gradlew
  - bash mvnw
  - docker-compose build --force-rm --no-cache --pull
  - docker-compose up --force-recreate --remove-orphans &
  - sleep 30
  - http :8080/webapp/
  - http :8080/webapp/hello-action
  - docker-compose down -v

  # struts2-angularjs-starter
  - cd ${base}/struts2-angularjs-starter
  - bash mvnw -f webapp/pom.xml clean package jetty:run &
  - wait_for 8080
  - http :8080/
  - http :8080/home
  - http :8080/projects
  - stop_any 8080

  # starter
  - cd ${base}/starter
  - bash gradlew clean build
  - bash mvnw clean package
  - docker-compose build --force-rm --no-cache --pull
  - docker-compose up --force-recreate --remove-orphans &
  - sleep 30
  - http :8080/webapp/
  - http :8080/webapp/hello
  - docker-compose down -v

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
