version: '2.1'

services:

  app:
    build: .
    ports:
      - '5005:5005'
      - '8080:8080'
      - '9990:9990'
    mem_limit: 786432000 # container limit: 750Mb (750 * 1024 * 1024)
    restart: unless-stopped
    networks:
      backing-services:
        aliases:
        - app
        - app.daggerok.com

networks:
  backing-services:
    driver: bridge
