version: "2.1"

services:

  webapp:
    build: .
    volumes: ["webapp-data:/home"]
    ports:
      - "5005:5005"
      - "8080:8080"
      - "9990:9990"
    mem_limit: 786432000
    networks: [backing-services]

volumes:
  webapp-data: {}

networks:
  backing-services:
    driver: bridge
